### ISSUE TITLE
PGliteInterface should implement Disposable [Symbol.dispose]

### ISSUE THREAD

**Issue by mlhaufe** [electric-sql/pglite#101]
TypeScript as of v5.2 added support for the Stage 3 ECMAScript Explicit Resource Management feature:

<https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management>

So instead of having to write:

```ts
const conn = new PGliteWorker(this._connString)

try {
    const result = await conn.query(...)
    // ...
    return parse(result)
} finally {
    // ...
    conn.close()
}
```

We can write:

```ts
using conn = new PGliteWorker(this._connString)

const result = await conn.query(...)
// ...
return parse(result)
```

I think it will be a nice usability win if `PGliteInterface` implements the  `Disposable` interface

**Comment by samwillis** [comment]
Hey, yep this would be a great use for these new features.

I would happily except a PR implementing it 👍

**Comment by fnacarellidev** [comment]
Hey @samwillis, I'm interest on trying to solve this issue, however I have no idea on where to start, could you possibly give me some pointers? :)
