### ISSUE TITLE
Other clients besides TypeScript-based ones like NodeJS, Bun, Deno

### ISSUE THREAD

**Issue by satvikpendem** [electric-sql/pglite#108]
Is there a way to use pglite without using JS/TypeScript as the client language? I was thinking since this packages up Postgres into WASM that others could then write bindings for other clients as well, such as for offline-first apps for Android via Kotlin, iOS via Swift, Flutter, etc.

**Comment by samwillis** [comment]
This is something I very much hope we can solve.

There are two routes are are looking at:
- a WASM only package with a lower level api for use without JS/TS
- a native C lib for binding to platforms without WASM support

There is a fair bit of cross over between the two, but also quite a bit of engineering to do to achieve it. It's on the roadmap.

**Comment by samwillis** [comment]
Closed in favour of #89
