### ISSUE TITLE
how can I use it with CJS?

### ISSUE THREAD

**Issue by MJRT** [electric-sql/pglite#113]
I try to use it on expo-web [with electric-sql](https://github.com/electric-sql/electric/issues/1423) or alone that all get error: 
> Uncaught Syntax Error: Cannot use 'import.meta' outside a module

**Comment by sombriks** [comment]
i got hit by similar issue, ts-node forced me to disable type module on package.json then when i tried to import PGlite it renders an error. 

works with tsx but need to test with pure commonjs node/js project yet.

**Comment by samwillis** [comment]
Hey, so far we've only published as ES modules. I intend to look at CJS again, it's on my radar. 

I'm suspicious we may find some things a little hard to replicate though, such as the automatic resolution of WASM and bundle files.

**Comment by sombriks** [comment]
nice to know that!

for instance the issue can be narrowed down specifically to ts-node, added alternative npm script using tsx, very same code, works perfectly, like the other pure js / type module projects!

**Comment by MJRT** [comment]
Hi @samwillis , exciting to see it, I understand you’re busy, and I’m also wondering if there’s a plan for when to start working on it?

**Comment by samwillis** [comment]
@MJRT I may have some time in the next week or so, but need to get a few other things sorted first before the new release goes final (there is an alpha out).

If not it will be soon after, but I don't yet know how much work it will be. I'm expecting to find complications.

**Comment by jamesgpearce** [comment]
I managed to get things running in Jest (which requires CJS) by using this babel plugin like so:

```
plugins: [
  ['babel-plugin-transform-import-meta', {module: 'ES6'}],  
  ...
```

HTH
