### ISSUE TITLE
Unable to load extensions in Web Worker

### ISSUE THREAD

**Issue by gregnr** [electric-sql/pglite#126]
The new extension system is amazing 🎉 but having an issue loading extensions in a Web Worker:

Works:

```typescript
import { PGlite } from '@electric-sql/pglite'
import { vector } from '@electric-sql/pglite/vector'

const db = new PGlite(`idb://my-db`, {
  extensions: {
    vector,
  },
})
```

Fails:

```typescript
import { PGliteWorker } from '@electric-sql/pglite/worker'
import { vector } from '@electric-sql/pglite/vector'

const db = new PGliteWorker(`idb://my-db`, {
  extensions: {
    vector,
  },
})
```

with error:

```
DOMException: Failed to execute 'postMessage' on 'Worker': async(s,n)=>({emscriptenOpts:n,bundlePath:/* asset import */ new __webpack_req...<omitted>...}) could not be cloned.
```

My best guess is something to do with being enable to serialize/wrap the `vector` module/function when sending to the Web Worker through `comlink`.

This is running in a Next.js application.

---

**Edit:** will likely be fixed by https://github.com/electric-sql/pglite/pull/120

**Comment by samwillis** [comment]
This is fixed in main with #120 merged. Will realise a new alpha later today.
