### ISSUE TITLE
Webpack doesn't automatically ignore all Node deps when bundling.

### ISSUE THREAD

**Issue by maurotrigo** [electric-sql/pglite#139]
After using [0.1.8](https://github.com/electric-sql/pglite/releases/tag/0.1.8) successfully, I'm now getting the following error while trying out these alpha releases:

- [v0.2.0-alpha.3](https://github.com/electric-sql/pglite/releases/tag/v0.2.0-alpha.3)
- [v0.2.0-alpha.4](https://github.com/electric-sql/pglite/releases/tag/v0.2.0-alpha.4)

```
./node_modules/@electric-sql/pglite/dist/index.js:1:21817
Module not found: Can't resolve 'stream/promises'
```

I'm doing this on a Next.js project v `13.5.3`. My webpack config on `next.config`:

```
webpack: (config, options) => {
	config.module.rules.push({
		test: /\.+(js|jsx|mjs|ts|tsx)$/,
		use: options.defaultLoaders.babel,
		// @ts-ignore
		include: fileURLToPath(import.meta.resolve('@electric-sql/pglite')),
		type: 'javascript/auto'
	});

	config.module.rules.push({
		test: /\.sql$/,
		// This is the asset module.
		type: 'asset/source'
	});

	if (!options.isServer) {
		config.resolve.fallback = { fs: false, module: false, path: false };
	}

	return config;
}
```

I'm not sure if I'm doing something wrong here. Please help!

**Comment by samwillis** [comment]
Hey @maurotrigo 

I have heard from others using Next.js that they had to add this to their config:

```js
config.resolve = {
      ...config.resolve,
      fallback: {
        fs: false,
        module: false,
        'stream/promises': false,
      },
    }
```

This will make webpack ignore some Node dependancies that are used within PGlite.

I'm going to keep this issue open, as I think we should look further into what we can do to make this work without specific webpack configs.

**Comment by samwillis** [comment]
We should add something like this to our `package.json`:

```js
"browser": {
  fs: false,
  module: false,
  'stream/promises': false,
}
```

The `browser` field is a hint to bundlers: https://github.com/defunctzombie/package-browser-field-spec

**Comment by maurotrigo** [comment]
> Hey @maurotrigo
> 
> I have heard from others using Next.js that they had to add this to their config:
> 
> ```js
> config.resolve = {
>       ...config.resolve,
>       fallback: {
>         fs: false,
>         module: false,
>         'stream/promises': false,
>       },
>     }
> ```
> 
> This will make webpack ignore some Node dependancies that are used within PGlite.
> 
> I'm going to keep this issue open, as I think we should look further into what we can do to make this work without specific webpack configs.

Hey @samwillis ,

This is perfect, I'm trying the latest version as well, works perfectly so far. 

Thank you so much!
