### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [electric-sql/pglite#14]
Hello, thank you for releasing this. Would you mind adding a license? Thank you!

**Comment by kevlened** [comment]
The package.json indicates it’s under Apache 2.0

https://github.com/electric-sql/pglite/blob/main/packages/pglite/package.json#L11

**Comment by fakerybakery** [comment]
Ah, thanks! Would be nice to have it specified so it's indicated on GitHub cc: @alco

**Comment by thruflo** [comment]
And yup, we’ll set that up clearly in the repo.

**Comment by fakerybakery** [comment]
Thanks!
