### ISSUE TITLE
Extension: pgvector

### ISSUE THREAD

**Issue by samwillis** [electric-sql/pglite#18]
Support pgvector extension

**Comment by LrWm3** [comment]
How does extension support work pglite? I think this is one of the most exciting aspects of pglite and would love to understand what it might look like as I have loved setting up postgres with custom extensions myself before and it would be cool to be able to figure that out for pglite as well.

Does the extension need to be included in the wasm bundle or can it be provided as a separate wasm artifact? Would plugins written with pgrx be easier to port?

Thanks for this exciting project!

**Comment by stereobooster** [comment]
Related: loading dynamic extensions compiled as WASM https://github.com/asg017/sqlite-loadable-rs/issues/5

**Comment by samwillis** [comment]
pgvector is supported in the current alpha/@next release, expected to go final in about a week.
