### ISSUE TITLE
Don't require building pglite in order to run the electric next sync demo

### ISSUE THREAD

**Issue by AntonOfTheWoods** [electric-sql/pglite#202]
https://github.com/electric-sql/pglite/tree/main/packages/pglite-sync/example

Requires the `pglite/dist` directory to be built. https://github.com/electric-sql/pglite/blob/446c2dfe7f62f2c80520f0c7ea7db454c875b54f/packages/pglite-sync/example/index.html#L10

That requires building `pglite`, which is still not trivial.

**Comment by samwillis** [comment]
The sync plugin is very new and under active development, once we have moved it further forward we intend to have installable examples and starters, but this example will remain like this as it is primarily used as a code sample, and for testing during development.

For building, **we are** working on making it ever to build locally using a Docker image.

If you want to build just the front end TS you can download the interim build files from GitHub CI and past them in /packages/pglite/release and then run `ppm build` to only do the second step. This is noted here: https://github.com/electric-sql/pglite?tab=readme-ov-file#how-to-contribute

**Comment by AntonOfTheWoods** [comment]
"you download from a comment under the most recently merged PR". I didn't understand this until now. People my age probably would understand it as "on" the PR, or even better "on the GitHub PR Issue".
