### ISSUE TITLE
PGliteWorker not working with drizzle

### ISSUE THREAD

**Issue by KiaClouth** [electric-sql/pglite#208]
OS: windows 11
Browser: chrome 127.0.6533.119
framework: solid-start

The minimal reproduction repository: [GitHub Repo Link](https://github.com/KiaClouth/solidstart-pglite-drizzle)

description:
I am using PGliteWorker with drizzle. I followed the instructions on https://pglite.dev/docs/multi-tab-worker to create a worker wrapper:
_PGliteWorker.ts_
`worker({
  async init() {
    const pg = await PGlite.create({...});
    await pg.exec(...);
    const db = drizzle(pg, { schema });
    const ret = await db.query.verification_token.findMany();
    console.log(ret);
    return pg;
  },
});`
I can see the results in the browser console. 
However, if I 
_entry-client.tsx_
`const pg = await PGliteWorker.create(
  new Worker(PGliteWorkerUrl, {
    type: "module",
  })
);
const db = drizzle(pg, { schema });
const ret = await db.query.verification_token.findMany();
console.log(ret);`

The browser console gives the following error:
Uncaught DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': value => value could not be cloned.
    at j.g (http://localhost:3001/_build/node_modules/.pnpm/@electric-sql+pglite@0.2.0/node_modules/@electric-sql/pglite/dist/worker/index.js?v=c34c2280:201:21)
    at j.query (http://localhost:3001/_build/node_modules/.pnpm/@electric-sql+pglite@0.2.0/node_modules/@electric-sql/pglite/dist/worker/index.js?v=c34c2280:98:56)
    at async PglitePreparedQuery.execute (http://localhost:3001/_build/node_modules/.vinxi/client/deps/drizzle-orm_pglite.js?v=d787a4e7:58:20)
    at async http://localhost:3001/_build/@fs/D:/ToramCalculator/src/entry-client.tsx:16:13

**Comment by TheAndrewJackson** [comment]
I've experienced this issue as well when trying to write to the DB with drizzle. My read queries were working. I wonder if this issue is an issue with drizzle

**Comment by samwillis** [comment]
The `Failed to execute 'postMessage' on 'BroadcastChannel'` error makes me think it could be our side as we use a BroadcastChannel to communicate with the worker. It's either:

- drizzle is trying to pass an un-cloneable object as a parameter to the query api.
- or we have something in our api that doesn't work with the worker and is not currently covered by the tests.
- or both, which is my suspicion:

I'm 99% sure we will find it's the `parser` query option (https://pglite.dev/docs/api#query-options) and will need a bit of a refactor.

**Comment by msfstef** [comment]
The issue seems to be that we are trying to transfer `ParserOptions` which contains anonymous functions to the worker without proper serialization.

Either the parsing is done at the calling thread (and the `ParserOptions` are stored and handled there) or we assume some limitations on the functions being passed and serialize them and deserialize them to run in the worker (e.g. with a `toString()/eval()` combination).

Since these parsers might depend on various imports and what not it might be better to handle deserialization in the caller.
