### ISSUE TITLE
dumpDataDir('none') is still returning a compressed file

### ISSUE THREAD

**Issue by jgoux** [electric-sql/pglite#225]
Hello 👋,

When passing the `none` option to `dumpDataDir`, it's always returning a compressed file instead of the expected `tar`.

I'm on `@electric-sql/pglite: "0.2.2"`.

**Comment by msfstef** [comment]
Hey, thank you for reporting!

On what platform/engine are you facing this issue? We have a test covering this and I can't reproduce the issue on Node or Chromium - setting the `dumpDataDir` argument to `none` produces an uncompressed `tar` file as expected.

Can you make sure this is reproducible with a clean install of `0.2.2`?

**Comment by msfstef** [comment]
Hey @jgoux - could you confirm if this is still an issue and if so if you have a path to reproduce it?

**Comment by jgoux** [comment]
I'm in holiday, will post a repro when I get back!

**Comment by msfstef** [comment]
Closing as no errors have been reported about this and am unable to reproduce + have test coverage! Feel free to reopen if you reproduce the errors though
