### ISSUE TITLE
Abstract away console logging?

### ISSUE THREAD

**Issue by jamesgpearce** [electric-sql/pglite#256]
Hello team! This is awesome so far.

One thing I'm getting, especially running PGLite in a test suite, is quite a lot of log spew:

```
console.log
  Running in main thread, faking onCustomMessage
  at Object.log [as 69039092] (node_modules/@electric-sql/pglite/dist/postgres.js:9:79806)

console.warn
  prerun(C-web) worker= false
  ...
  etc
```

I can patch the console implementation to get around this for now, but it would great if you had some sort of verbose/quite mode, or a way to abstract away the informational messages if I don't need them.

Thanks!

**Comment by samwillis** [comment]
Hey @jamesgpearce 

Thanks for the report (I'm excited by the concept of TinyBase havingPGlite support!)

That's some stray debug logging that we meant to silence.

@pmp-p could you tidy this up, I think it may be coming some an Emscripten block? Could we swap it to Module.print() so it picked up the the debug level in the main PGlite code?
