### ISSUE TITLE
Typing for PgliteInterface.query method

### ISSUE THREAD

**Issue by sampbarrow** [electric-sql/pglite#300]
`query<R>(query: string, params?: any[] | undefined, options?: QueryOptions | undefined): Promise<Results<R>>`

Is there any reason the params argument needs to be mutable? Could the type be `readonly any[]` or `readonly unknown[]`?

**Comment by samwillis** [comment]
Hey @sampbarrow, thanks for the suggestion, but we are going to leave it as is for now as I don't think it gains us anything.
