### ISSUE TITLE
`Failed to resolve './' from './node\_modules/@electric-sql/pglite/dist/postgres.js'`

### ISSUE THREAD

**Issue by ashrielbrian** [electric-sql/pglite#328]
I am using [Plasmo](https://github.com/PlasmoHQ/plasmo) to build a Chrome extension with `pglite` as the persistent data store running in a background worker. 

Backing plasmo is, I believe, a node server running a live hot reload for each new change. However, when I try to load pglite in my background worker script, i.e.

```ts
import { PGlite } from "@electric-sql/pglite";
```

I get the errors:

```
🔴 ERROR  | Failed to resolve './' from './node\_modules/@electric-sql/pglite/dist/postgres.js'
🔴 ERROR  | Cannot load file './' in './node\_modules/@electric-sql/pglite/dist'.
```

Looking into `postgres.js` I believe the culprit is on line 318:
```javascript
  scriptDirectory = require('url').fileURLToPath(new URL("./", import.meta.url)); // includes trailing slash
```

I removed `"./"`:

```javascript
scriptDirectory = require('url').fileURLToPath(new URL(import.meta.url)); // includes trailing slash
```

and it was able to find the modules correctly. This was something that only occurred specifically with `pglite`, and not other modules/packages I had installed.

Versions:

```
"@electric-sql/pglite": "0.2.7"
"plasmo": "0.89.2"
```

**Comment by seanmorris** [comment]
I think this Emscripten patch should fix it.
https://github.com/emscripten-core/emscripten/pull/22605/files

**Comment by seanmorris** [comment]
Just replace new URL('./', import.meta.url) with new URL('./', Object(import.meta).url) if you don't want webpack to touch it.

**Comment by seanmorris** [comment]
> 0.2.10 should build with newer emscripten, did it fix the problem ?

Looks like it was still pre-patch. Line 321 still shows the old notation that messes with webpack:

https://www.npmjs.com/package/@electric-sql/pglite?activeTab=code

The patch we need was introduce to Emscripten in commit `543993ecf6fbf1c97c2ed56d062dc504978962c3`:

https://github.com/emscripten-core/emscripten/commit/

**Comment by seanmorris** [comment]
I'm seeing this working with WebPack and PGlite v0.2.11.
