### ISSUE TITLE
v0.2.8 and v0.2.9 - Module not found: Can't resolve 'fs/promises'

### ISSUE THREAD

**Issue by lirbank** [electric-sql/pglite#355]
I tried to upgrade `@electric-sql/pglite` from 0.2.7 to 0.2.8 yesterday, and then again today to 0.2.9, with the same result.

Here is the build output:

```sh
> next build 

  ▲ Next.js 15.0.0-canary.161
  - Environments: .env

   Creating an optimized production build ...
Failed to compile.

../../node_modules/.pnpm/@electric-sql+pglite@0.2.9/node_modules/@electric-sql/pglite/dist/chunk-AZTFRW3V.js
Module not found: Can't resolve 'fs/promises'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../node_modules/.pnpm/@electric-sql+pglite@0.2.9/node_modules/@electric-sql/pglite/dist/index.js
```

I have PGlite running with Next.js 15 like a charm with 0.2.7, per https://github.com/electric-sql/pglite/issues/322#issuecomment-2372563526

**Comment by villegasrfael** [comment]
Same as @lirbank Even forcing the detection of 'fs/promises' returns an error

ERROR Error: Invalid FS bundle size: 21268 !== 2987856

**Comment by samwillis** [comment]
Hey @lirbank, @villegasrfael

Thanks for the report! I think I know whats happened, I made some changes to enable supplying the wasm bin and VFS bundle manually and it changes some of these code paths. This is top of the list for early this week.

**Comment by lirbank** [comment]
Nice @samwillis ! - when do you think you'll publish a new package to NPM? I'd love to try the new version.
