### ISSUE TITLE
Calling postgres.wasm from Python

### ISSUE THREAD

**Issue by psychemedia** [electric-sql/pglite#40]
Hi 

I was wondering if it's possible to make use of `postgres.wasm` from Python using something like `wastime` PyPi package.

This could provide a handy way of supporting educational activities using postgres without having to ship a PostgreSQL server.

Is there any documentation on the `postgres.wasm` package, it's exports, etc?

**Comment by samwillis** [comment]
Hey @psychemedia 

We haven't yet worked on making `postgres.wasm` portable to other runtimes, it's JS only at the moment. However we hope to make these use cases possible in future.

**Comment by psychemedia** [comment]
Thanks for the info, @samwillis ; I was just trying to explore possible use cases of having `postgres-wasm`; looking forward to py compatability;-)

Will close issue...
