### ISSUE TITLE
'@electric-sql/pglite' does not provide an export named 'NodeFS'

### ISSUE THREAD

**Issue by GeorgiosP** [electric-sql/pglite#413]
Looking at the docs for node / bun its listing NodeFS for retaining content in the file system for some persistence any assistance would be greatly appreciated! 

https://pglite.dev/docs/filesystems#node-fs

using version 0.2.12

cannot use NodeFS since its saying it does not exist 😢

**Comment by pmp-p** [comment]
postgres.js node build is in interim archive and does support FS ( i use it with bun and pglite-server/pg-gateway everyday), if it says NodeFS is missing then the postgres.js picked up is probably the web version.

**Comment by GeorgiosP** [comment]
Got it! is it also included in the PGLite since I'm using that here? 

I'm running PGLite on my server not in client but the only way I've managed to get it to play nice is using `memory://` during PGLite setup

**Comment by GeorgiosP** [comment]
Sweet! I'll give that a shot 🙏🏼

**Comment by GeorgiosP** [comment]
Closing this out for now appreciate the support 🫡  unpack works well but its not super sustainable
