### ISSUE TITLE
support db tool content

### ISSUE THREAD

**Issue by Hiram-Wong** [electric-sql/pglite#428]
If the data is saved locally, I want it to be managed through a visual DB tool, maybe chat2db or navicat

**Comment by yacineb** [comment]
@Hiram-Wong if you need to use a visual db tool which connects to your pglite instance, you can run somewhere a proxy server,  add a websocket client within the app running pglite which connects to that proxy. 

An simply connect your visual db client to your proxy host:port.

and  please check this project https://github.com/kamilogorek/pglite-server
