### ISSUE TITLE
Export the return type of syncShapeToTable so that it can be used outside lib

### ISSUE THREAD

**Issue by samwillis** [electric-sql/pglite#451]

**Comment by thruflo** [comment]
Also it would be helpful to include the `stream` in the return value. This is to allow components to match on it. I've recently added this to the `useShape` React hook as per:

```ts
const { data, stream } = useShape({...})
```

It would be nice to be able to access the same thing from `syncShapeToTable`, i.e.:

```ts
const { stream } = await pglite.electric.syncShapeToTable({
  shape: {...},
  ...
})
```

**Comment by yacineb** [comment]
Closed by https://github.com/electric-sql/pglite/pull/452
