### ISSUE TITLE
Param ordering inconsistent with Electric client.

### ISSUE THREAD

**Issue by thruflo** [electric-sql/pglite#454]
Electric recently merged https://github.com/electric-sql/electric/pull/2044 to consistent sort query params to maximise cache hits. I have an example app with pure Electric and PGlite components in the same page. I noticed that the PGlite sync requests have params in a different order to the pure Electric requests:

<img width="620" alt="image" src="https://github.com/user-attachments/assets/66e02571-0baa-4eda-8604-e6b7d71b051c">

I'm aware that I'm using electric from the ppm workspace and PGlite as a versioned deployment:

```json
"@electric-sql/client": "workspace:*",
"@electric-sql/pglite": "^0.2.14",
"@electric-sql/pglite-react": "^0.2.14",
"@electric-sql/pglite-sync": "^0.2.16",
"@electric-sql/react": "workspace:*",
```

So this may just be a versioning thing but I'm guessing the PGlite sync doesn't use the Typescript client under the hood (or does it)?

**Comment by samwillis** [comment]
It does use the code Electric client internally, so I suspect this is version thing... we'll double check. It's probably bringing in the published version with then runs in parallel along side the workspace one.

**Comment by KyleAMathews** [comment]
The change hasn't been released yet

https://github.com/electric-sql/electric/pull/2046

**Comment by thruflo** [comment]
Ok great 👍
