### ISSUE TITLE
extension: pg_trgm

### ISSUE THREAD

**Issue by zachblume** [electric-sql/pglite#50]
`support for similarity of text using trigram matching`
https://www.postgresql.org/docs/current/pgtrgm.html

Use case for me for pglite:
- Offloading work from the DB to instant read replicas living inside serverless functions
- pg_trgm is commonly used for string comparisons and provides the `GIN` and `GIST` index handling

**Comment by samwillis** [comment]
pg_trgm is supported in the current alpha/@next release, expected to go final in about a week.
