### ISSUE TITLE
Rebase on Postgres v16

### ISSUE THREAD

**Issue by samwillis** [electric-sql/pglite#57]
Currently PGlite uses a fork or pg v15, we should rebase on v16

**Comment by AntonOfTheWoods** [comment]
@samwillis there seem to be short instructions for rebuilding with the currently supported v15 version. Apart from rebasing and fixing any potential conflicts, are there any other things to do? I seem to be finding lots of stability issues and it would be good to see if an upgrade makes them go away (almost certainly not but hey!).

v17 is also just around the corner, so if there were an easyish procedure then that would allow for motivated souls to get some initial testing out of the way...

**Comment by samwillis** [comment]
Hey @AntonOfTheWoods 

The new version we are building is based on v16.2, I'm pull it should be ready in about two weeks. The intention is to have a patches ready for v17 on release too.

The new version is a significant refactor that unlocks dynamically runtime loaded extensions and has much better error handling.
