### ISSUE TITLE
Question: How to access it from a GUI?

### ISSUE THREAD

**Issue by BrunoQuaresma** [electric-sql/pglite#65]
Hi folks, I'm playing around with the project and I'm using local files to store the data. Is there any GUI that would support pqlite? I would like to use it to debug things. Thank you!

**Comment by samwillis** [comment]
We've not built one yet, but it's on the list!

best way to debug for now it to make the db global so you can access it from the terminal, then just do queries there.

**Comment by jlucaso1** [comment]
It's possible to use something like drizzle studio?

**Comment by jueinin** [comment]
but i want to use it on browser, is there a GUI tool to view database?

**Comment by jueinin** [comment]
in browser env, may be you can try this project, https://github.com/datawan-labs/pg

 just import src/main.tsx and provideo a container DOM node.

ensure import it within the same domain & port, otherwise, it can't read the pg indexdb files

**Comment by Jonovono** [comment]
@jlucaso1 you can use drizzle studio https://github.com/drizzle-team/drizzle-orm/issues/2823

**Comment by f0rr0** [comment]
Hey, I built https://github.com/f0rr0/pg-browser-proxy which lets you use any tool - drizzle studiol, prisma studio, psql etc. to interact with browser based databases. Check it out!

**Comment by thruflo** [comment]
@f0rr0 super cool!
