### ISSUE TITLE
Calling `execProtocol` when PGlite is not ready

### ISSUE THREAD

**Issue by jgoux** [electric-sql/pglite#74]
Hey, it's me again. 😄

`execProtocol` is not checking if the database is ready, which triggers this error when called externally to send wire protocol messages:

> TypeError: undefined is not an object (evaluating 'this.emp._malloc')

I see 3 solutions:
- Calling `await this.#checkReady();` in the `execProtocol` function
- Keeping `execProtocol` as is for internal use within `PGlite` but exposing a version with `await this.#checkReady();` applied
- Making `PGlite` extends `EventEmitter` and emits a `ready` event when ready (my favorite solution)

In the end, I think `execProtocol` is exposed for low-level implementations such as `pglite-server` so I wouldn't do extra work in `execProtocol`.

**Comment by samwillis** [comment]
Adding note here for others after we chatted on Discord here: https://discord.com/channels/933657521581858818/1212676471588520006/1225898205292793928

Good idea on making PGlite an EventEmitter, we should do that, and it's needed for when we support pg_notify.

It's currently possible to await `pg.waitReady`, this is a promise that resolves at the end of the `init`. We can't wait for that inside `execProtocol` as `execProtocol` is itself used inside the `init` and that would result in a deadlock.

I've purposely not documented `execProtocol` yet as I want feedback on its design, and whats the best way for it to work for the server simulation use case.

We could have public and privet versions of `execProtocol`, an internal one without `waitRead` and a public one with it.

**Comment by jgoux** [comment]
I missed `waitReady`! For now, it's more than enough for my use case. 👍

**Comment by samwillis** [comment]
With `waitReady` and the newer static `await PGlite.create()` I think adding the await to `execProtocol` will add more complexity and so I'm going to close this issue.
