### ISSUE TITLE
error performing snapshot: error: unrecognized node type: 67143218

### ISSUE THREAD

**Issue by AntonOfTheWoods** [electric-sql/pglite#93]
When trying to electrify with `  electric = await electrify(conn, schema, config);` I am reasonably regularly getting these errors. Typically a ctrl+f5 resolves the issue. This may be due to `electric` or the integration but I didn't see it with `sqlite`

**Comment by samwillis** [comment]
This error it related to the legacy Electric sync, and so I'm going to close it.
