### ISSUE TITLE
Error: expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

### ISSUE THREAD

**Issue by barbalex** [electric-sql/pglite#96]
I tried to use pglite instead of sqlite: https://github.com/barbalex/ps/commit/5c3c44f731c6e492e9ee150cd97e64ba61dfb093, following these: https://electric-sql.com/blog/2024/05/14/electricsql-postgres-client-support, https://electric-sql.com/docs/integrations/drivers/web/pglite

When starting the app (after rebuilding docker, migrating the db, generating the client and emptying the browser cache) this error appears in the console:
```console
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -sASSERTIONS for more info
```
<img width="574" alt="Screenshot 2024-06-02 124248" src="https://github.com/electric-sql/pglite/assets/669783/66be0aff-6b96-4bb3-9338-0a5809b7d6d2">

I probably flubbed the migration?

I am working on Windows 11 using nodejs v22.2.0

Also tried it on my MacOS notebook. Same error.

**Comment by lecstor** [comment]
I get the same message when calling `new PGlite()` in a newly generated Vite app. 

<img width="555" alt="Screenshot 2024-06-05 at 7 42 44 AM" src="https://github.com/electric-sql/pglite/assets/1168602/b0f0144a-388c-4136-92f7-155554ab56c8">
<img width="685" alt="Screenshot 2024-06-05 at 7 44 22 AM" src="https://github.com/electric-sql/pglite/assets/1168602/a108be70-3380-4e07-bf6e-2c1866426589">

**Comment by lecstor** [comment]
**Solved**

@barbalex maybe have a look at your server setup, it appears that error is due to the wasm file not being served correctly.

https://github.com/WebAssembly/spec/issues/1031
> Those bytes are "<!DO" in ASCII, so probably you are trying to load an HTML document.

I was able to resolve this using the Vite config from the sqlite-wasm readme.. https://github.com/sqlite/sqlite-wasm?tab=readme-ov-file#usage-with-vite

<img width="525" alt="Screenshot 2024-06-05 at 8 20 29 AM" src="https://github.com/electric-sql/pglite/assets/1168602/34488552-4322-4cb4-81c2-fccf6694835f">

<img width="678" alt="Screenshot 2024-06-05 at 8 21 07 AM" src="https://github.com/electric-sql/pglite/assets/1168602/7dd5e455-0734-4ef4-a17a-411054f630f8">

**Comment by barbalex** [comment]
@lecstor Thanks a lot. Your input solved the issue.

In case others bump into this when migrating from using sqlite: I had these issues to solve:

1. exclude `@electric-sql/pglite` in optimizeDeps in vite.config.ts as mentioned by @lecstor: https://github.com/barbalex/ps/blob/pglite/vite.config.ts#L9-L17
2. import `electrify` from `electric-sql/pglite`, no more from `electric-sql/wa-sqlite` (I had forgotten to change that): https://github.com/barbalex/ps/blob/ce105ae1b806f5adc94441ab4f5e09da35660b5e/src/ElectricWrapper.tsx#L3
3. Now `npm i` failed due to better-sqlite3 failing to build native sqlite (it seems that electric-sql@0.11.3 needs better-sqlite3). I had to downgrade my local node.js from 22.2 to the 20.x lts version (dont know why this didn't happen earlier)

Now I am running into issues due to `syntax error at or near "PRAGMA"`. But I guess that is to be expected as the app uses pragma to set up on startup and that has to be altered for postgre-sql.

**Comment by barbalex** [comment]
issue solved
